### ISSUE TITLE
Error[102] Read PGM Version and Config!

### ISSUE THREAD

**Issue by MagnusErler** [pvvx/TLSRPGM#3]
I'm following [tb-0x-kit-pgm](https://github.com/pvvx/TLSRPGM/tree/main/sources/UART2SWire/tb-0x-pgm) but am receiving the following error when executing the command.
```
python TlsrPgm.py -p /dev/ttyUSB1 -t5000 we 0 sources/UART2SWire/uart2swire.bin 
=======================================================
TLSR82xx TlsrPgm version 12.11.23
-------------------------------------------------------
Open /dev/ttyUSB1, 230400 bit/s... ok
Error[102] Read PGM Version and Config!
```

I have a [TB-03F-KIT](https://www.aliexpress.com/item/1005002781870238.html?spm=a2g0o.order_list.order_list_main.36.27dc1802zwqUGC) and have connected SWS to pin 2 of CH340

**Comment by pvvx** [comment]
[README.md](https://github.com/pvvx/TLSRPGM/tree/main/sources/UART2SWire/tb-0x-pgm#readme)

```
python3 TlsrComProg.py -p COM7 -t5000 we 0 ../urat2swire.bin
```

[TlsrComProg.py](https://github.com/pvvx/TlsrComProg825x)
