### ISSUE TITLE
Clarification on the Usable Devices

### ISSUE THREAD

**Issue by TheFrozenDuck** [pvvx/TLSRPGM#8]
I am a bit confused about one of the first sentences in the readme and want to make sure before doing some major mistake.

> Use TB-04-KIT or TB-04 / 03F module (TLSR8253 chip) and USB-COM PL2303HX or CH430 chip.

To my understanding, the following options would be valid:

- TB-04-KIT,
- TB-04 / 03F module (TLSR8253 chip) in combination with a USB-COM PL2303HX,
- or CH340-based device

Does that mean that I can use a CH340-based (I suppose CH430 is a typo?) to directly flash a new firmware?

**Comment by pvvx** [comment]
For the initial recording of a program in the TLSR8253, almost any USB-COM with 3.3V outputs is suitable.
It is advisable to use the specified chips to operate the programmer. The work has not been tested on other options.

**Comment by TheFrozenDuck** [comment]
Thank you very much for the clarification :grin:

**Comment by TheFrozenDuck** [comment]
One last question popped up:

Regarding the mapping of the ports VCC and GND are pretty straight forward. In addition the CH340 has TX and RX labelled. Am I correct to assume that TX is to be connected to SWS, and RX to RST?

**Comment by pvvx** [comment]
1. [Diagram for initial programming.](https://github.com/pvvx/TlsrComProg825x)
2. In the working version of the programmer, disconnect the resistor from the circuit.

**Comment by TheFrozenDuck** [comment]
Thank you, I didn't realise that the information exists in a differnt repo.
